/*import 'package:flutter/material.dart';
import '../services/distribution_services.dart';
import '../model/distribution_model.dart';

class AddEditDistributionView extends StatefulWidget {
  final Distribution? distribution;

  AddEditDistributionView({this.distribution});

  @override
  _AddEditDistributionViewState createState() => _AddEditDistributionViewState();
}

class _AddEditDistributionViewState extends State<AddEditDistributionView> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _vehiclePlateController;
  late TextEditingController _dateController;
  late TextEditingController _officerNameController;

  @override
  void initState() {
    super.initState();
    _vehiclePlateController = TextEditingController(text: widget.distribution?.vehiclePlate);
    _dateController = TextEditingController(text: widget.distribution?.date);
    _officerNameController = TextEditingController(text: widget.distribution?.officerName);
  }

  @override
  void dispose() {
    _vehiclePlateController.dispose();
    _dateController.dispose();
    _officerNameController.dispose();
    super.dispose();
  }

  void _saveDistribution() async {
    if (_formKey.currentState!.validate()) {
      final distribution = Distribution(
        id: widget.distribution?.id ?? '', // For new distributions, this might be generated by the backend
        guid: '',
        guidCompany: '',
        vehiclePlate: _vehiclePlateController.text,
        date: _dateController.text,
        officerName: _officerNameController.text,
        guidOfficer: '',
        boxQty: 0,
        createdAt: DateTime.now(),
      );

      final service = DistributionService();
      try {
        if (widget.distribution == null) {
          await service.createDistribution(distribution);
        } else {
          await service.updateDistribution(widget.distribution!.id, distribution);
        }
        Navigator.pop(context);
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.distribution == null ? 'Add Distribution' : 'Edit Distribution'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _vehiclePlateController,
                decoration: InputDecoration(labelText: 'Vehicle Plate'),
                validator: (value) => value!.isEmpty ? 'Please enter vehicle plate' : null,
              ),
              TextFormField(
                controller: _dateController,
                decoration: InputDecoration(labelText: 'Date'),
                validator: (value) => value!.isEmpty ? 'Please enter date' : null,
              ),
              TextFormField(
                controller: _officerNameController,
                decoration: InputDecoration(labelText: 'Officer Name'),
                validator: (value) => value!.isEmpty ? 'Please enter officer name' : null,
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: _saveDistribution,
                child: Text('Save'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}*/
